# Generated by Django 5.0 on 2024-03-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(blank=True, choices=[(10, 10), (11, 11)], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.CharField(blank=True, choices=[('Дівчина', 'Дівчина'), ('Юнак', 'Юнак')], max_length=256, null=True),
        ),
    ]
