# Generated by Django 5.0 on 2024-01-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolsclassrooms'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schools'),
        ),
    ]
