version: '3.9'
services:
  server:
    container_name: sport-connect-api
    restart: always
    build:
      context: .
    environment:
      DJANGO_SUPERUSER_PASSWORD: "root"
      DJANGO_SUPERUSER_USERNAME: "root"
      DJANGO_SUPERUSER_EMAIL: "root@root.com"
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_started

  celery_worker:
    container_name: sport-connect-api-celery-worker
    image: celery:latest
    restart: always
    build:
        context: .
    entrypoint: /app/entrypoints/celery-worker-entrypoint.sh
    env_file:
      - ".env"
    volumes:
      - .:/app
    depends_on:
      server:
        condition: service_started
      database:
        condition: service_started
      redis:
        condition: service_started

  flower:
    container_name: sport-connect-api-flower
    restart: always
    build:
        context: .
    entrypoint: /app/entrypoints/celery-flower-entrypoint.sh
    env_file:
      - ".env"
    volumes:
      - .:/app
      - flower_data:/data
    expose:
      - 5555
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_started
      celery_worker:
        condition: service_started
      server:
        condition: service_started

  database:
    image: postgres:15
    container_name: sport-connect-api-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sport_connect_db
    volumes:
      - sport-connect-api-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: sport-connect-api-redis
    restart: always
    ports:
      - "6379:6379"

  nginx:
    container_name: sport-connect-nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf.d:/etc/nginx/nginx-conf.d
      - static:/app/static
      - media:/app/media
    depends_on:
      server:
        condition: service_started

volumes:
  static:
  media:
  flower_data:
  sport-connect-api-data:
