version: '3.9'
services:
  server:
    container_name: sport-connect-api
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/DockerfileProd
    command: /django
    environment:
      DATABASE_HOST: "postgres"
      DJANGO_SUPERUSER_PASSWORD: "root"
      DJANGO_SUPERUSER_USERNAME: "root"
      DJANGO_SUPERUSER_EMAIL: "root@root.com"
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    env_file:
      - ".env"
    ports:
      - "8000:8000"

  celery_worker:
    container_name: celery-worker
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/DockerfileProd
    command: /start-celeryworker
    environment:
      DATABASE_HOST: "postgres"
    env_file:
      - ".env"
    volumes:
      - .:/app
      - media:/app/media
      - redis_data:/var/lib/redis
      - flower_data:/var/lib/flower
    depends_on:
      - server
      - redis

  flower:
    build:
      context: .
      dockerfile: dockerfiles/DockerfileProd
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - '.env'
    ports:
      - "5557:5555"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis

  nginx:
    container_name: nginx-api
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
      - ./nginx-conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - server

  certbot:
    container_name: certbot-api
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  static:
  media:
  flower_data:
  redis_data:
  sport-connect-api-data:
