version: '3.9'
services:
  server:
    container_name: sport-connect-api
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: /django
    environment:
      DATABASE_HOST: "postgres"
      DJANGO_SUPERUSER_PASSWORD: "root"
      DJANGO_SUPERUSER_USERNAME: "root"
      DJANGO_SUPERUSER_EMAIL: "root@root.com"
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    depends_on:
      - database

  celery_worker:
    container_name: celery-worker
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: /start-celeryworker
    environment:
      DATABASE_HOST: "postgres"
    env_file:
      - ".env"
    volumes:
      - .:/app
      - media:/app/media
      - redis_data:/var/lib/redis
      - flower_data:/var/lib/flower
    depends_on:
      - server
      - rabbitmq



  flower:
    container_name: flower
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ".env"
    ports:
      - "5557:5555"
    depends_on:
      - rabbitmq
      - database

  database:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sport_connect_db
    volumes:
      - sport-connect-api-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.13.0-management
    container_name: rabbitmq
    restart: always
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  nginx:
    container_name: nginx-api
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
      - ./nginx-conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - server




volumes:
  static:
  media:
  flower_data:
  redis_data:
  sport-connect-api-data:


