version: '3.9'
services:
  server:
    container_name: sport-connect-api
    restart: always
    build: .
    environment:
      DATABASE_HOST: "postgres"
      DJANGO_SUPERUSER_PASSWORD: "root"
      DJANGO_SUPERUSER_USERNAME: "root"
      DJANGO_SUPERUSER_EMAIL: "root@root.com"
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_started

  celery_worker:
    container_name: celery-worker
    image: celery:latest
    restart: always
    build: .
    entrypoint: /app/entrypoints/celery-worker-entrypoint.sh
    environment:
      DATABASE_HOST: "sport-connect-api-postgres"
    env_file:
      - ".env"
    volumes:
      - .:/app
      - media:/app/media
      - redis_data:/var/lib/redis
      - flower_data:/var/lib/flower
    depends_on:
      server:
        condition: service_started
      database:
        condition: service_started
      redis:
        condition: service_started

  flower:
    container_name: sport-connect-api-flower
    restart: always
    build: .
    entrypoint: /app/entrypoints/celery-flower-entrypoint.sh
    environment:
      DATABASE_HOST: "sport-connect-api-postgres"
    env_file:
      - ".env"
    volumes:
      - .:/app
      - redis_data:/var/lib/redis
      - flower_data:/var/lib/flower
    expose:
      - 5555
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_started
      celery_worker:
        condition: service_started
      server:
        condition: service_started

  database:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sport_connect_db
    volumes:
      - sport-connect-api-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis

#  nginx:
#    container_name: nginx-api
#    image: nginx:latest
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx-conf.d:/etc/nginx/conf.d
#      - .:/app
#      - static:/app/static
#      - media:/app/media
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#    depends_on:
#      server:
#        condition: service_started
#
#  certbot:
#    container_name: certbot-api
#    image: certbot/certbot
#    depends_on:
#      - nginx
#    volumes:
#      - ./nginx-conf.d:/etc/nginx/conf.d
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot

volumes:
  static:
  media:
  flower_data:
  redis_data:
  sport-connect-api-data:
