version: '3.11'
services:
  server:
    container_name: sport-connect-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: /django
    environment:
      DATABASE_HOST: "postgres"
      DJANGO_SUPERUSER_PASSWORD: "root"
      DJANGO_SUPERUSER_USERNAME: "root"
      DJANGO_SUPERUSER_EMAIL: "root@root.com"
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    depends_on:
      - database

  celery_worker:
    container_name: celery-worker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: /start-celeryworker
    environment:
      DATABASE_HOST: "postgres"
    env_file:
      - ".env"
    volumes:
      - .:/app
      - media:/app/media
    depends_on:
      - server
      - rabbitmq

  flower:
    container_name: flower
    build:
      context: .
      dockerfile: Dockerfile
    command: /start-flower
    environment:
      DATABASE_HOST: "postgres"
    volumes:
      - .:/app
    env_file:
      - ".env"
    ports:
      - "5557:5555"
    depends_on:
      - rabbitmq
      - database

  database:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sport_connect_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  rabbitmq:
    image: rabbitmq:3.13.0-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "8080:15672"

  nginx:
    container_name: nginx-api
    image: nginx:latest
    restart: always
    ports:
      - "8081:80"
    volumes:
      - static:/app/static
      - media:/app/media
      - ./nginx-conf.d:/etc/nginx/conf.d
    depends_on:
      - server

volumes:
  static:
  media:
  flower_data:
  postgres_data:
  rabbitmq:
