version: '3.11'
services:
  server:
    container_name: server
    restart: always
    build: .
    command: /django
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    env_file: ".env"
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - database

  redis:
    image: redis:latest
    container_name: redis-main
    volumes:
      - redis_data:/var/lib/redis/data
    ports:
      - "127.0.0.1:6379:6379"

  celery_worker:
    container_name: celery-worker
    restart: always
    build: .
    command: /start-celeryworker
    environment:
      DATABASE_HOST: "postgres"
    env_file: ".env"
    volumes:
      - .:/app
      - media:/app/media
    depends_on:
      - server
      - redis

  database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ".env"
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  static:
  media:
  postgres_data:
  redis_data:
