# Generated by Django 5.0 on 2024-01-27 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AverageValuesStandards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_standard', models.CharField(max_length=225, verbose_name='Показник')),
                ('children_age', models.IntegerField(choices=[(10, 10), (11, 11)], null=True, verbose_name='Вік дитини')),
                ('children_gender', models.CharField(choices=[('Юнак', 'Юнак'), ('Дівчина', 'Дівчина')], max_length=225, null=True, verbose_name='Стать дитини')),
                ('average_value', models.FloatField(null=True, verbose_name='Середнє значення')),
                ('sigma', models.FloatField(verbose_name='Сигма')),
            ],
            options={
                'verbose_name': 'Середні значення по нормативах',
                'verbose_name_plural': 'Середні значення по нормативах',
                'db_table': 'average_values_standards',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Вид спорту',
                'verbose_name_plural': 'Види спорту',
                'db_table': 'sports',
            },
        ),
        migrations.CreateModel(
            name='SportSchool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=350)),
                ('school_site_url', models.URLField()),
                ('school_sport_address', models.CharField(max_length=350)),
                ('school_sport_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('school_sport_phone_numbers', models.CharField(blank=True, max_length=500, null=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_schools', to='core.sport')),
            ],
            options={
                'verbose_name': 'Сайт ДЮСШ',
                'verbose_name_plural': 'Сайти ДЮСШ',
                'db_table': 'sport_school',
            },
        ),
        migrations.CreateModel(
            name='WeightingFactors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weighting_factor', models.FloatField(verbose_name='Ваговий коефіцієнт')),
                ('average_value_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighting_factors', to='core.averagevaluesstandards')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighting_factors', to='core.sport')),
            ],
            options={
                'verbose_name': 'Вагові коефіцієнти (за випробуваннями)',
                'verbose_name_plural': 'Вагові коефіцієнти (за випробуваннями)',
                'db_table': 'weighting_factors',
            },
        ),
    ]
