# Generated by Django 5.0 on 2024-06-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='averagevaluesstandards',
            old_name='name_standard',
            new_name='standard',
        ),
    ]
