# Generated by Django 5.0 on 2024-06-26 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_standard_averagevaluesstandards_standard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportstandard',
            options={'verbose_name': 'Норматив', 'verbose_name_plural': 'Нормативи'},
        ),
        migrations.AlterField(
            model_name='weightingfactors',
            name='average_value_standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighting_factors', to='core.sportstandard', verbose_name='Норматив'),
        ),
    ]
