# Generated by Django 5.0 on 2024-06-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sportstandard_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightingfactors',
            old_name='average_value_standard',
            new_name='sport_standard',
        ),
    ]
