# Generated by Django 5.0 on 2025-02-12 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sportstandard_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResult',
        ),
    ]
