# Generated by Django 5.0 on 2024-06-15 12:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_averagevaluesstandards_name_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportStandard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225, verbose_name='Назва стандарту')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
