# Generated by Django 5.0 on 2024-06-15 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sportstandard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagevaluesstandards',
            name='name_standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sportstandard', verbose_name='Показник'),
        ),
    ]
